### ISSUE TITLE
Store weights in thunks

### ISSUE THREAD

**Issue by calintat** [sdvisualiser/sd-visualiser#66]
It would be useful to allow thunks to carry weights (of a different type than operations).

I would like to store thunk addresses (from the language) in the thunk instead of in the output edge, which would not work if we allow thunks to have multiple outputs or if we allow users to bind thunks to variables (does MLIR allow this?).

**Comment by alexarice** [comment]
What's a thunk address from the language?

**Comment by calintat** [comment]
The `%2` in 

```
def main(id: %1) : (Float64) -> Float64 = func(
    thunk %2 = { x(id: %3) : Float64 =>
        def %5 = plus(x(id: %3), %4)
        output %5
    }
)
output %4
```

**Comment by calintat** [comment]
This is only in chil not spartan

**Comment by alexarice** [comment]
Right, sounds good
